exports.createHouse = require('./create')
exports.findHouseByOneParam = require('./findByOneParam')
exports.findHouseById = require('./findById')
exports.deleteHouse = require('./delete')
exports.findAll = require('./findAll')